/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    FootComponent: typeof import('./src/components/FootComponent.vue')['default']
    HeadComponent: typeof import('./src/components/HeadComponent.vue')['default']
    NoResultView: typeof import('./src/components/NoResultView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VendorListComponent: typeof import('./src/components/vendorListComponent.vue')['default']
  }
}
